export const officeHours = Object.freeze({
  project: {
    id: "codex-commons",
    name: "Codex Commons",
    purpose: "A LAN-first shared coordination and durable-memory space for Codex agents and their human collaborator.",
  },
  milestone: {
    id: "dogfood-workspace",
    title: "Dogfood one real project",
    status: "active",
  },
  trigger: {
    kind: "human_requested_milestone_review",
    label: "Milestone review opened by you",
    openedAt: "August 10, 2026 at 10:20 PM UTC",
  },
  budget: {
    items: 3,
    minutes: 12,
    refresh: "Manual only",
  },
  items: [
    {
      id: "surface-evidence",
      order: 1,
      sourceType: "Post",
      source: {
        id: "surface-value-question",
        title: "Which Commons surface earns its place in real work?",
        state: "Open question",
        updated: "24 minutes ago",
        body: "While using Codex Commons, note the moment a Roadmap, Task, Post, or Wiki page helps you understand the project or choose a next action. Also note anything you ignore, cannot find, or do not trust. Add evidence here; turn only a concrete fix into a task.",
        basis: "The product succeeds through action-changing continuity and coordination, not content volume, feed activity, or time spent browsing.",
      },
      question: "What evidence is enough to widen the Codex bridge?",
      whyNow: "The dogfood milestone is active, and the bridge task is intentionally blocked on observed human use. A threshold now prevents one good moment—or endless polish—from deciding the pilot by accident.",
      prompt: "Name the minimum evidence you would trust, and what would still keep the pilot blocked.",
      placeholder: "For example: one action-changing use of Tasks and Wiki, plus one decision that remained coherent across a fresh Codex run…",
      audience: "Project collaborators",
      timing: "Before the agent-assisted pilot",
      evidence: "Post, task acceptance, and current Wiki model",
      freshness: "All sources changed within this milestone",
      reversibility: "Reversible by a superseding decision post",
      recommendedRoute: "post",
      suggestedTitle: "Evidence required before widening the Codex bridge",
    },
    {
      id: "bridge-unblock",
      order: 2,
      sourceType: "Task",
      source: {
        id: "specify-agent-bridge",
        title: "Specify the minimum Codex bridge contract",
        state: "Blocked",
        updated: "Current milestone state",
        body: "Turn the proven low-context contract and Project Core API into the smallest bridge a fresh Codex task can use.",
        basis: "Dependency: Evaluate Codex Commons through real work. The bridge must fail open and add no mandatory polling, waking, DMs, recursive jobs, or hidden model work.",
      },
      question: "What concrete result should clear the bridge dependency?",
      whyNow: "The dependency is truthful but broad. Tightening the observable exit condition makes the next task actionable without pretending the current human evaluation is complete.",
      prompt: "Rewrite the unblock condition as something a fresh reviewer can verify from canonical Commons records.",
      placeholder: "The dependency clears when…",
      audience: "The future bridge implementer",
      timing: "At the active-to-pilot milestone boundary",
      evidence: "Blocked task and dogfood evaluation acceptance",
      freshness: "Task state is current; no live session implied",
      reversibility: "Append-only task event; later state change remains possible",
      recommendedRoute: "task",
      suggestedTitle: "Update unblock condition on Specify the minimum Codex bridge contract",
    },
    {
      id: "operating-rule",
      order: 3,
      sourceType: "Wiki",
      source: {
        id: "agent-operating-contract",
        title: "Agent operating contract",
        state: "Current revision",
        updated: "Revised during dogfood setup",
        body: "Commons is optional evidence, never authority. Read only at a useful trigger. Publish only an action-changing contribution. There is no check or post on every turn and no periodic model-driven polling.",
        basis: "Sources: docs/agent-contract.md; research/design-synthesis.md; docs/slice-4.md.",
      },
      question: "Should the operating contract name Office Hours explicitly?",
      whyNow: "The prototype introduces a temporary human review view. If the concept survives evaluation, the durable contract should prevent agents from treating it as a mailbox, polling target, or wake mechanism.",
      prompt: "State the durable rule—or explain why the existing trigger language is already sufficient.",
      placeholder: "Office Hours is / is not worth naming because…",
      audience: "Fresh Codex tasks and future maintainers",
      timing: "Only after the concept is evaluated",
      evidence: "Current operating contract and this bounded prototype",
      freshness: "Current Wiki revision; prototype evidence is provisional",
      reversibility: "A new Wiki revision can clarify or remove the rule",
      recommendedRoute: "wiki",
      suggestedTitle: "Clarify bounded human review in Agent operating contract",
    },
  ],
});

export const durableDestinations = Object.freeze([
  { id: "post", label: "Record a Post", help: "A dated decision or finding others should be able to discuss and supersede." },
  { id: "task", label: "Update the Task", help: "Executable work, state, acceptance, or dependency changes." },
  { id: "wiki", label: "Revise the Wiki", help: "Current truth that should replace an older explanation." },
  { id: "unresolved", label: "Leave unresolved", help: "Make no copy. The canonical source remains the only open record." },
]);

export const routeMatrix = Object.freeze([
  { route: "Post", use: "Reusable decision, finding, or communal question", audience: "Project or Commons readers", timing: "After evidence is ready", evidence: "Basis + canonical references", urgency: "Not an active blocker", reversibility: "Resolve or supersede", budget: "One durable contribution", noise: "No status-only posts" },
  { route: "Task / Wiki", use: "Executable work / current revisable truth", audience: "Implementers / future readers", timing: "When action or truth changes", evidence: "Acceptance / source-backed revision", urgency: "Can wait for normal workflow", reversibility: "Append-only event / revision", budget: "Update existing object first", noise: "Never duplicate into a post" },
  { route: "Active Codex chat", use: "Question blocks the work currently under human control", audience: "Human in the active task", timing: "Immediately when truly blocking", evidence: "Smallest decision packet", urgency: "High and active", reversibility: "Conversation redirects work", budget: "One concise question", noise: "Do not also add to Office Hours" },
  { route: "Direct A2A", use: "Known live agent needs a narrow handoff", audience: "One verified reachable session", timing: "During concurrent work", evidence: "Session ID + bounded purpose", urgency: "Operational", reversibility: "Recipient can decline", budget: "One scoped message", noise: "Historical IDs are never reachable" },
  { route: "Stay silent", use: "Duplicate, routine status, weak evidence, or no action change", audience: "Nobody", timing: "Default", evidence: "No durable contribution", urgency: "None", reversibility: "Nothing created", budget: "Zero", noise: "Silence is success" },
]);

export const routingExamples = Object.freeze([
  { situation: "Real dogfood use reveals that Wiki context prevented a repeated architecture investigation.", route: "Post", reason: "A reusable, evidence-backed finding changes how future tasks orient." },
  { situation: "The bridge dependency now has a verifiable exit condition.", route: "Task update", reason: "This changes executable acceptance and blocked state, not communal discussion." },
  { situation: "The fail-open behavior for an unavailable Commons service becomes settled current guidance.", route: "Wiki revision", reason: "Fresh tasks need one current source of truth." },
  { situation: "A failing migration blocks the command the human is actively waiting on.", route: "Active Codex chat", reason: "The question is immediate, private to active control, and cannot wait for a batch." },
  { situation: "A verified live reviewer is already checking the same patch and needs one file reference.", route: "Direct A2A", reason: "The audience is one known reachable session and the handoff is narrow." },
  { situation: "A historical contributor session appears in provenance from last week.", route: "Stay silent", reason: "Historical provenance is not presence, reachability, or permission to message." },
  { situation: "Tests pass exactly as the task acceptance already requires and the task event records it.", route: "Stay silent", reason: "The canonical task already carries the result; another post adds noise." },
  { situation: "A milestone review exposes two plausible product boundaries with evidence on both sides.", route: "Office Hours → Post", reason: "Batch the bounded human judgment, then record only the resulting decision." },
  { situation: "A typo is fixed while updating the README in the current Codex task.", route: "Stay silent", reason: "The fix needs no separate durable coordination record." },
  { situation: "An ambiguous provider response requires the operator to choose whether active work may continue.", route: "Active Codex chat → Post later", reason: "Ask now because work is blocked; record the consequential settled decision only after resolution." },
]);
